### ISSUE TITLE
Need Help------Redirect Uri for the Google Sigin and Github 

### ISSUE THREAD

**Issue by skgupta507** [rajput-hemant/infinitunes#49] opened 2024-08-27 05:34 UTC
Hey @rajput-hemant 
Can u help me with the Redirect use used for the Github and Google signin.
i have used [https://infinitunesx.vercel.app/__/auth/handler](url) for github but it says application misconfigured or server configuration error.
can u help me regarding this pls.
the below image is the error iam facing. for both google and github signin

![image](https://github.com/user-attachments/assets/4ad03284-c8a7-4c43-8828-90e4fe03136c)

**Comment by skgupta507** [comment] 2024-08-27 06:51
Hey @rajput-hemant @viruop  @Khushal-ag i think i found the issue which is the database table not Getting created correctly.
alredy created the tables. screenshot attached below.

![image](https://github.com/user-attachments/assets/f5e51514-0bb6-41b2-95be-b9b8f010548f)

used the `npx drizzle-kit generate` command to create the tables. but it dosent work.

also attaching the vercel logs for ur reference.

[logs_result.json](https://github.com/user-attachments/files/16757813/logs_result.json)

**Comment by Gupta507** [comment] 2024-09-27 07:14
hey @rajput-hemant iam also facing the same issue
the site works but during login it gives me the same error can u help me resolve this error.

**Comment by rajput-hemant** [comment] 2024-09-27 19:48
Hey @skgupta507, @Gupta507,
Please pull the new changes and check if it resolves the issue. I've attached a video below showing no issues with signing in on my end. If you still encounter the error, it would be helpful if you could provide a screen recording or detailed steps to reproduce. Thanks!

https://github.com/user-attachments/assets/d4cec59e-c745-459a-b2f2-d609bea59549

**Comment by skgupta507** [comment] 2024-09-28 06:54
> Hey @skgupta507, @Gupta507, Please pull the new changes and check if it resolves the issue. I've attached a video below showing no issues with signing in on my end. If you still encounter the error, it would be helpful if you could provide a screen recording or detailed steps to reproduce. Thanks!
> 
>  compressed.mov

Hi @rajput-hemant iam attaching the vercel log for ur reference as iam still facing the issue.
<img width="957" alt="image" src="https://github.com/user-attachments/assets/b66b29a9-4ddc-45c8-8a51-abf4370c2dce">

**Comment by inthelovedotorg** [comment] 2024-10-02 14:26
I'm also facing the same issue, can you please provide a bit assistance hemant, it would be really appreciated. Ive tried signing in on your hosted website and it's working there perhaps we are doing something wrong can you please assist us

**Comment by inthelovedotorg** [comment] 2024-10-03 03:20
@skgupta507 @Gupta507 if you guys are still having problem, i figured it out the actual problem was userId being defined as a text in account table and the other table like playlists etc had userId defined as uuid so if you want to manually fix it- 

Just go to your supabase database go to the tables section,

 find the account table and there you'll see a userId section, with a drop down arrow next to it, click on it you'll see an edit button, click on edit then you'll see a page with alot of stuff to edit but you just need to edit it from text to uuid and once you do it save it and then try it everything will be alright

**Comment by skgupta507** [comment] 2024-10-04 14:18
> @skgupta507 @Gupta507 if you guys are still having problem, i figured it out the actual problem was userId being defined as a text in account table and the other table like playlists etc had userId defined as uuid so if you want to manually fix it-
> 
> Just go to your supabase database go to the tables section,
> 
> find the account table and there you'll see a userId section, with a drop down arrow next to it, click on it you'll see an edit button, click on edit then you'll see a page with alot of stuff to edit but you just need to edit it from text to uuid and once you do it save it and then try it everything will be alright

I @inthelovedotorg thanks for the Solution Bro its working now.

But can u help with the REDIRECT_uri for Github.

**Comment by inthelovedotorg** [comment] 2024-10-04 14:28
for redirect_uri for GitHub you can do it by adding authorised url on GitHub oauth by -
 -   https://<yourwebname>.vercel.app/api/auth/callback/github

I think in your case I see your webapp name to be infinitunesx so it'll be

https://infinitunesx.vercel.app/api/auth/callback/github

**Comment by skgupta507** [comment] 2024-10-04 14:32
> @skgupta507 for redirect_uri for GitHub you can do it by adding authorised url on GitHub oauth by -
> 
> * https://{yourwebname}.vercel.app/api/auth/callback/github
> 
> I think in your case I see your webapp name to be infinitunesx so it'll be
> 
> https://infinitunesx.vercel.app/api/auth/callback/github

Hi bro,
thanks it works now .
Ur help was much appriciated.

**Comment by inthelovedotorg** [comment] 2024-10-06 05:41
@rajput-hemant you can close this up, the issue is solved 👍🏻

**Comment by rajput-hemant** [comment] 2024-10-07 07:11
thanks for helping us out with resolving this issue, really appreciate your support!

**Closed by rajput-hemant** 2024-10-07 07:11 UTC
